ConfigStorage
const String ConfigStorage::config_path
const int ConfigStorage::default_lock_state
const String ConfigStorage::default_remote_address
const String ConfigStorage::default_auth_hash
char ConfigStorage::authHash[36][36]
Referenced by Load, Save, WebServer::Init.
char ConfigStorage::controlServerAddress[255][255]
Referenced by Load, Save.
byte ConfigStorage::lockState
Referenced by AccessControl::NextCard, Load, Save.
void ConfigStorage::Init()
References Load.
Referenced by setup.
void ConfigStorage::Load()
References authHash, controlServerAddress, lockState.
Referenced by Init.
void ConfigStorage::Save()
References authHash, controlServerAddress, lockState.
Referenced by WebServer::Init.