@startuml
(*) --> "Новий запит"
--> "checkCard(request)"
--> "Отримати данні про IP адресу"
--> "Пошук пристрою по IP адресі"
--> if "Пристрій знайдено?" then
    -> [Так] "Отримання даних про унікальний номер картки"
    --> "Пошук карти по унікальному номеру"
    --> if "Картку знайдено?" then
          -> [Так] "Отримати інформацію про роль"
                    --> if "Чи має картка роль?" then
                       -> [Так] "Отрима дані про дозволені пристрої" 
                              --> if "Чи відповідає знайдений пристрій дозволений пристроям ролі?" then
                                -> [Так] "Формування запиту що доступ надано"
                                --> "Відправка відповіді що доступ надано"
                              else
                                --> [Ні] "Формування запиту що картка не має ролі"
                                --> "Відправка відповіді що доступ заборонено з причиною заборони"
                              endif
                        else
                          --> [Ні] "Формування запиту що картка не має ролі"
                          --> "Відправка відповіді що доступ заборонено з причиною заборони"
                        endif
        else
          --> [Ні] "Формування запиту що картку не знайдено"
          --> "Відправка відповіді що доступ заборонено з причиною заборони"
        endif
    else 
    --> [Ні] "Формування запиту що пристрій не знайдено"
    --> "Відправка відповіді що доступ заборонено з причиною заборони"
    -->(*)
    endif
@enduml