name: CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install packages
      run: cd ./ui && npm install
  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Run project linter
      run: cd ./ui && npm run build
  compile:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Run project compiler
      run: cd ./ui && npm run build
